"""Regenerate the self-hosted webfont subsets and `fonts.css` under `frontend/static/fonts/`.

    python ops/fetch-fonts.py    # one-shot and wired into nothing: the build stays offline
"""

from __future__ import annotations

import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
FONTS = REPO / "frontend" / "static" / "fonts"
STYLESHEET = FONTS / "fonts.css"

# css2 answers by User-Agent; urllib's own UA gets ttf and static per-weight files.
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# Other subsets would be dead weight in the all-or-nothing service-worker precache.
SUBSETS = ("latin-ext", "latin")

# Constants so a test can re-render the stylesheet offline; `fetch_faces()` checks them live.
UNICODE_RANGES = {
    "latin-ext": (
        "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, "
        "U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, "
        "U+2113, U+2C60-2C7F, U+A720-A7FF"
    ),
    "latin": (
        "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, "
        "U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, "
        "U+FEFF, U+FFFD"
    ),
}


@dataclass(frozen=True)
class Family:
    name: str
    slug: str
    weights: tuple[int, ...]
    styles: tuple[str, ...] = ("normal",)


# §6.8's one webfont (decision 527): interface text is the device's own font, titles are this.
FAMILIES = (Family("Instrument Serif", "instrument-serif", (400,), ("normal", "italic")),)

HEADER = """\
/* Generated by ops/fetch-fonts.py. Do not hand-edit.
 *
 * Self-hosted, and that is load-bearing rather than a preference: §6's preamble makes this an
 * installable PWA a household opens over the LAN and over Tailscale, and app.html says the same
 * thing over its own <link> -- a blocking stylesheet from a third-party host would make the
 * shell wait on a host it may not be able to reach. Latin and latin-ext subsets only.
 *
 * Interface text uses the device's own font; Instrument Serif sets titles (§6.8, decision 527).
 */
"""

FACE = """
/* {subset} */
@font-face {{
  font-family: '{name}';
  font-style: {style};
  font-weight: {weight};
  font-display: swap;
  src: url(/fonts/{file}) format('woff2');
  unicode-range: {ranges};
}}
"""

# WOFF2 spec, Table 1: tags by 5-bit index. Index 63 means the tag follows inline.
WOFF2_KNOWN_TAGS = (
    "cmap", "head", "hhea", "hmtx", "maxp", "name", "OS/2", "post", "cvt ", "fpgm",
    "glyf", "loca", "prep", "CFF ", "VORG", "EBDT", "EBLC", "gasp", "hdmx", "kern",
    "LTSH", "PCLT", "VDMX", "vhea", "vmtx", "BASE", "GDEF", "GPOS", "GSUB", "EBSC",
    "JSTF", "MATH", "CBDT", "CBLC", "COLR", "CPAL", "SVG ", "sbix", "acnt", "avar",
    "bdat", "bloc", "bsln", "cvar", "fdsc", "feat", "fmtx", "fvar", "gvar", "hsty",
    "just", "lcar", "mort", "morx", "opbd", "prop", "trak", "Zapf", "Silf", "Glat",
    "Gloc", "Feat", "Sill",
)


def woff2_tables(data: bytes) -> list[str]:
    """The table tags a woff2 declares, read from its uncompressed directory (no brotli needed)."""
    if data[:4] != b"wOF2":
        raise ValueError("not a woff2 file")
    count = int.from_bytes(data[12:14], "big")
    offset = 48
    tags: list[str] = []

    def base128() -> int:
        nonlocal offset
        value = 0
        while True:
            byte = data[offset]
            offset += 1
            value = (value << 7) | (byte & 0x7F)
            if not byte & 0x80:
                return value

    for _ in range(count):
        flags = data[offset]
        offset += 1
        index = flags & 0x3F
        if index == 63:
            tag = data[offset:offset + 4].decode("latin1")
            offset += 4
        else:
            tag = WOFF2_KNOWN_TAGS[index]
        base128()  # origLength
        # For glyf/loca, version 0 IS the transform; a transformed entry has a second length.
        version = (flags >> 6) & 0x3
        transformed = version == 0 if tag in ("glyf", "loca") else version != 0
        if transformed:
            base128()
        tags.append(tag)
    return tags


def file_name(family: Family, weight: int, style: str, subset: str) -> str:
    italic = "-italic" if style == "italic" else ""
    return f"{family.slug}-{weight}{italic}-{subset}.woff2"


def file_for(
    family: Family, weight: int, subset: str, fonts_dir: Path = FONTS, style: str = "normal"
) -> str:
    """A static family has a file per weight and style; a variable one (`fvar`) serves every
    weight from the file named for its base weight."""
    own = file_name(family, weight, style, subset)
    if (fonts_dir / own).is_file() or style != "normal":
        return own
    base = f"{family.slug}-{min(family.weights)}-{subset}.woff2"
    path = fonts_dir / base
    if not path.is_file():
        raise FileNotFoundError(f"neither {own} nor {base} is in {fonts_dir}")
    if "fvar" not in woff2_tables(path.read_bytes()):
        raise ValueError(f"{base} carries no wght axis, so it cannot serve weight {weight}")
    return base


def render_css(families: tuple[Family, ...] = FAMILIES, fonts_dir: Path = FONTS) -> str:
    blocks = [HEADER]
    for family in families:
        for style in family.styles:
            for weight in family.weights:
                for subset in SUBSETS:
                    blocks.append(
                        FACE.format(
                            subset=subset,
                            name=family.name,
                            style=style,
                            weight=weight,
                            file=file_for(family, weight, subset, fonts_dir, style),
                            ranges=UNICODE_RANGES[subset],
                        )
                    )
    return "".join(blocks)


def _get(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def _one(pattern: str, block: str, what: str) -> str:
    found = re.search(pattern, block)
    if found is None:
        raise SystemExit(f"a Google Fonts @font-face block declares no {what}: {block.strip()!r}")
    return found.group(1)


_BLOCK = re.compile(r"/\*\s*([a-z0-9-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", re.S)


def fetch_faces(family: Family) -> dict[tuple[int, str, str], str]:
    """The woff2 URL per (weight, style, subset). css2 answers a weight outside the axis with HTTP 400."""
    ital = [1 if style == "italic" else 0 for style in family.styles]
    weights = ";".join(f"{i},{w}" for i in ital for w in family.weights)
    query = f"family={urllib.parse.quote_plus(family.name)}:ital,wght@{weights}&display=swap"
    try:
        css = _get(f"https://fonts.googleapis.com/css2?{query}").decode("utf-8")
    except urllib.error.HTTPError as exc:
        raise SystemExit(
            f"Google Fonts refused {family.name} at weights {weights} with HTTP {exc.code}. "
            f"A weight outside the family's wght axis is rejected, so check the axis before "
            f"declaring the face."
        ) from exc

    found: dict[tuple[int, str, str], str] = {}
    for subset, block in _BLOCK.findall(css):
        if subset not in SUBSETS:
            continue
        ranges = _one(r"unicode-range:\s*([^;]+);", block, "unicode-range").strip()
        if ranges != UNICODE_RANGES[subset]:
            raise SystemExit(
                f"Google's {subset} range for {family.name} is no longer the one this script "
                f"holds. Update UNICODE_RANGES and re-read what the new range drops.\n"
                f"  theirs: {ranges}\n  ours:   {UNICODE_RANGES[subset]}"
            )
        weight = int(_one(r"font-weight:\s*(\d+)", block, "font-weight"))
        style = _one(r"font-style:\s*(\w+)", block, "font-style")
        found[(weight, style, subset)] = _one(r"src:\s*url\((\S+?)\)", block, "src")

    missing = [
        (w, st, s) for w in family.weights for st in family.styles for s in SUBSETS
        if (w, st, s) not in found
    ]
    if missing:
        raise SystemExit(f"Google Fonts served no {family.name} face for {missing}")
    return found


def main() -> int:
    downloads: dict[str, bytes] = {}
    for family in FAMILIES:
        faces = fetch_faces(family)
        # One name per distinct URL; sorted so `setdefault` keeps the lowest weight, the name
        # app.html preloads.
        names: dict[str, str] = {}
        for weight, style, subset in sorted(faces, key=lambda key: (key[2], key[1], key[0])):
            names.setdefault(faces[(weight, style, subset)], file_name(family, weight, style, subset))
        for url, name in names.items():
            data = _get(url)
            if data[:4] != b"wOF2":
                raise SystemExit(f"{url} did not answer with a woff2 file")
            downloads[name] = data
        print(f"{family.name}: {len(faces)} faces over {len(names)} files")

    FONTS.mkdir(parents=True, exist_ok=True)
    for name, data in sorted(downloads.items()):
        (FONTS / name).write_bytes(data)
        kind = "variable" if "fvar" in woff2_tables(data) else "static"
        print(f"  wrote {name} ({len(data)} bytes, {kind})")

    # The service worker precaches this whole directory, so a stale file costs every phone.
    for path in sorted(FONTS.glob("*.woff2")):
        if path.name not in downloads:
            path.unlink()
            print(f"  removed {path.name}, which no face declares any more")

    STYLESHEET.write_text(render_css(), encoding="utf-8")
    print(f"  wrote {STYLESHEET.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
